### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by justinwestmoreland** [justinwestmoreland/Project-1#4]
Gabe, create the wireframe

**Comment by GQuak** [comment]
<img width="464" alt="WhoSaidIt_HighScores_Wireframe" src="https://user-images.githubusercontent.com/75180482/106842222-d9172b80-6660-11eb-8885-827017fa328f.png">
<img width="465" alt="WhoSaidIt_StartPage_Wireframe" src="https://user-images.githubusercontent.com/75180482/106842224-d9afc200-6660-11eb-8ade-9d047f78829c.png">
<img width="467" alt="WhoSaidIt_Wireframe" src="https://user-images.githubusercontent.com/75180482/106842225-d9afc200-6660-11eb-9d85-48658c51b5a9.png">
